#!/usr/bin/env python2
#encoding:utf-8
#author:Ether009
#project:anidb_api
#repository:http://github.com/Ether009/anidb_indexer
#license:unlicense (http://unlicense.org/)

"""Custom exceptions used or raised by anidb_api"""

__author__ = "Ether009"
__version__ = "1.0"

__all__ = ["anidb_error", "anidb_userabort", "anidb_shownotfound",
"anidb_seasonnotfound", "anidb_episodenotfound", "anidb_attributenotfound"]

class anidb_exception(Exception):
    """Any exception generated by tvrage_api
    """
    pass

class anidb_error(anidb_exception):
    """An error with tvrage.com (Cannot connect, for example)
    """
    pass

class anidb_userabort(anidb_exception):
    """User aborted the interactive selection (via
    the q command, ^c etc)
    """
    pass

class anidb_shownotfound(anidb_exception):
    """Show cannot be found on anidb.info (non-existant show)
    """
    pass

class anidb_seasonnotfound(anidb_exception):
    """Season cannot be found on tvrage.com
    """
    pass

class anidb_episodenotfound(anidb_exception):
    """Episode cannot be found on tvrage.com
    """
    pass

class anidb_attributenotfound(anidb_exception):
    """Raised if an episode does not have the requested
    attribute (such as a episode name)
    """
    pass
